import { beforeEach, describe, expect, it } from "vitest";

// themes.ts keeps the choice in localStorage and announces it on window
const mem = new Map<string, string>();
(globalThis as any).localStorage = { getItem: (k: string) => mem.get(k) ?? null, setItem: (k: string, v: string) => void mem.set(k, v) };
const events: CustomEvent[] = [];
(globalThis as any).window = { dispatchEvent: (e: CustomEvent) => events.push(e) };
(globalThis as any).CustomEvent ??= class<T> extends Event { detail: T; constructor(t: string, o: { detail: T }) { super(t); this.detail = o.detail; } };

const th = await import("../../src/modules/themes");

describe("terminal colour schemes", () => {
  beforeEach(() => { mem.clear(); events.length = 0; });

  it("maps Windows Terminal names to xterm.js ones", () => {
    const [s] = th.parseSchemes(JSON.stringify({ name: "X", background: "#000000", foreground: "#ffffff", purple: "#aa00aa", brightPurple: "#ff00ff", cursorColor: "#00ff00", selectionBackground: "#333333" }));
    expect(s.name).toBe("X");
    expect(s.colors).toEqual({ background: "#000000", foreground: "#ffffff", magenta: "#aa00aa", brightMagenta: "#ff00ff", cursor: "#00ff00", selectionBackground: "#333333" });
  });

  it("reads the schemes list of settings.json with comments and trailing commas", () => {
    const json = `// This file was initially generated by Windows Terminal
      { "profiles": { "list": [] },
        /* colour schemes */
        "schemes": [
          { "name": "A", "background": "#111", "foreground": "#eee", },
          { "name": "no colours" },
          { "name": "B", "background": "#222222", "foreground": "#dddddd", "red": "not a colour" },
        ],
      }`;
    const list = th.parseSchemes(json);
    expect(list.map((x) => x.name)).toEqual(["A", "B"]);
    expect(list[1].colors.red).toBeUndefined();
  });

  it("accepts a plain list and rejects junk", () => {
    expect(th.parseSchemes(`[{"background":"#000","foreground":"#fff"}]`)[0].name).toBe("Импорт");
    expect(() => th.parseSchemes("not json")).toThrow(/не JSON/);
    expect(() => th.parseSchemes(`{"schemes": [{"name": "x"}]}`)).toThrow(/нет цветовых схем/);
  });

  it("keeps imported schemes, replaces by name and applies the choice", () => {
    expect(th.currentThemeName()).toBe("OpsDeck");
    expect(th.currentTheme().background).toBe("#0f1117");
    th.addThemes([{ name: "Mine", colors: { background: "#010101", foreground: "#fefefe" } }]);
    th.addThemes([{ name: "Mine", colors: { background: "#020202", foreground: "#fefefe" } }]);
    expect(th.allThemes().filter((x) => x.name === "Mine")).toHaveLength(1);
    th.setTheme("Mine");
    expect(th.currentTheme().background).toBe("#020202");
    expect(events.at(-1)?.type).toBe("term-theme");
    expect(events.at(-1)?.detail.background).toBe("#020202");
    // a built-in scheme can be overridden by an import of the same name
    th.addThemes([{ name: "Dracula", colors: { background: "#123456", foreground: "#fff" } }]);
    expect(th.allThemes().filter((x) => x.name === "Dracula")).toHaveLength(1);
    // an unknown saved name falls back to the default
    th.setTheme("gone");
    expect(th.currentTheme().background).toBe("#0f1117");
  });

  it("every built-in scheme has valid colours", () => {
    for (const t of th.BUILTIN) for (const v of Object.values(t.colors)) expect(v, t.name).toMatch(/^#[0-9a-f]{6}$/i);
  });
});
